
package GUI_Menu;

public class Central_sel extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Central_sel */
    public Central_sel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        GeDeCe = new javax.swing.JCheckBox();
        GeShPaBe = new javax.swing.JCheckBox();
        GeShPaCl = new javax.swing.JCheckBox();
        GeRaWaBe = new javax.swing.JCheckBox();
        GeRaWaTrCl = new javax.swing.JCheckBox();
        GeRaWaReCl = new javax.swing.JCheckBox();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Centrality selection");

        jLabel11.setText("Please select the centralities to compute. Be aware that betweeness");

        jLabel12.setText("computation might take long time.");

        GeDeCe.setText("Generalized Degree Centrality");
        GeDeCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeDeCeActionPerformed(evt);
            }
        });

        GeShPaBe.setText("Generalized Shortest Path Betweennes");
        GeShPaBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeShPaBeActionPerformed(evt);
            }
        });

        GeShPaCl.setText("Generalized Shortest Path Closeness");
        GeShPaCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeShPaClActionPerformed(evt);
            }
        });

        GeRaWaBe.setText("Generalized Random Walk Betweennes");
        GeRaWaBe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeRaWaBeActionPerformed(evt);
            }
        });

        GeRaWaTrCl.setText("Generalized Random Walk Transmitter Closeness");
        GeRaWaTrCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeRaWaTrClActionPerformed(evt);
            }
        });

        GeRaWaReCl.setText("Generalized Random Walk Receiver Closeness");
        GeRaWaReCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeRaWaReClActionPerformed(evt);
            }
        });

        ok.setText("ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(GeRaWaReCl)
                            .add(GeRaWaTrCl)
                            .add(GeShPaCl)
                            .add(GeShPaBe)
                            .add(GeDeCe)
                            .add(jLabel11)
                            .add(jLabel12)
                            .add(GeRaWaBe)))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(166, 166, 166)
                        .add(ok)))
                .add(0, 37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel12)
                .add(18, 18, 18)
                .add(GeDeCe)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(GeShPaBe)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(GeShPaCl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(GeRaWaBe)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(GeRaWaTrCl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(GeRaWaReCl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(ok))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void GeDeCeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void GeShPaBeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void GeShPaClActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void GeRaWaBeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void GeRaWaTrClActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void GeRaWaReClActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void okActionPerformed(java.awt.event.ActionEvent evt) {                                   
    	setVisible(false);
    }                                  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Central_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Central_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Central_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Central_sel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Central_sel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox GeDeCe;
    private javax.swing.JCheckBox GeRaWaBe;
    private javax.swing.JCheckBox GeRaWaReCl;
    private javax.swing.JCheckBox GeRaWaTrCl;
    private javax.swing.JCheckBox GeShPaBe;
    private javax.swing.JCheckBox GeShPaCl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton ok;
    // End of variables declaration                   
    
}
